export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const PRODUCTS_LOADED = 'PRODUCTS_LOADED';
export const SET_PRODUCT = 'SET_PRODUCT';
export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const SET_PRODUCT_CLICKED = 'SET_PRODUCT_CLICKED';
